# Generated by Django 4.2.5 on 2023-09-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(upload_to='product'),
        ),
    ]
