# Generated by Django 4.2.5 on 2023-09-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_nome_produto_nome_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(choices=[('PF', 'Perfumes'), ('LO', 'Locoes'), ('SH', 'Shampoos'), ('CO', 'Condicionadores'), ('CR', 'Cremes'), ('DE', 'Desodorantes'), ('SA', 'Sabonetes'), ('ES', 'Esmaltes'), ('SA', 'Sabonetes'), ('MA', 'Maquiagens')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
