# Generated by Django 4.2.5 on 2023-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_produto_consumidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_desejos',
            name='esta_no_carrinho',
            field=models.BooleanField(default=False),
        ),
    ]
