# Generated by Django 4.2.5 on 2023-10-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_lista_desejos_esta_no_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_desejos',
            name='esta_no_carrinho',
        ),
    ]
