# Generated by Django 4.2.5 on 2023-10-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_remove_lista_desejos_esta_no_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='composicao',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(max_length=650),
        ),
    ]
